force-app/main/default/objects/Token__c/Token__c.object-meta.xml
<CustomObject>
    <label>Token</label>
    <nameField>
        <label>Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Token__c/fields/Near_Alert_Sent__c.field-meta.xml
<CustomField>
    <fullName>Near_Alert_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Near Alert Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Position_In_Queue__c.field-meta.xml
<CustomField>
    <fullName>Position_In_Queue__c</fullName>
    <label>Position In Queue</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TokenNearAlertQueueable.cls
public class TokenNearAlertQueueable implements Queueable {

    private List<Id> tokenIds;

    public TokenNearAlertQueueable(List<Id> tokenIds) {
        this.tokenIds = tokenIds;
    }

    public void execute(QueueableContext context) {

        List<Token__c> tokens = [
            SELECT Id, Email__c, Name,
                   Token_Number__c,
                   Position_In_Queue__c,
                   Near_Alert_Sent__c
            FROM Token__c
            WHERE Id IN :tokenIds
        ];

        List<Messaging.SingleEmailMessage> emails =
            new List<Messaging.SingleEmailMessage>();

        List<Token__c> tokensToUpdate =
            new List<Token__c>();

        for (Token__c t : tokens) {

            Messaging.SingleEmailMessage mail =
                new Messaging.SingleEmailMessage();

            mail.setToAddresses(new List<String>{ t.Email__c });
            mail.setSubject('SmartQueue – Your Turn is Near!');
            mail.setPlainTextBody(
                'Hello ' + t.Name + ',\n\n' +
                'Your token number: ' + t.Token_Number__c + '\n' +
                'Current Position: ' + t.Position_In_Queue__c + '\n\n' +
                'Please be ready. Your turn is coming soon.\n\n' +
                'SmartQueue System'
            );

            emails.add(mail);

            t.Near_Alert_Sent__c = true;
            tokensToUpdate.add(t);
        }

        if (!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }

        if (!tokensToUpdate.isEmpty()) {
            update tokensToUpdate;
        }
    }
}