force-app/main/default/objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>Service Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Token__c/Token__c.object-meta.xml
<CustomObject>
    <label>Token</label>
    <nameField>
        <label>Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Token__c/fields/Position_In_Queue__c.field-meta.xml
<CustomField>
    <fullName>Position_In_Queue__c</fullName>
    <label>Position In Queue</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Tokens</relationshipLabel>
    <relationshipName>Tokens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Near</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Token__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LiveQueueBoardController.cls
public with sharing class LiveQueueBoardController {

    @AuraEnabled(cacheable=true)
    public static List<Token__c> getLiveQueue(Id serviceCenterId){

        return [
            SELECT Id, Token_Number__c, Status__c, Position_In_Queue__c
            FROM Token__c
            WHERE Service_Center__c = :serviceCenterId
            AND Status__c = 'Waiting'
            ORDER BY Position_In_Queue__c ASC
            LIMIT 5
        ];

    }

}